"""
Library Transitivity Extractor — Parses Gradle dependency tree output to extract
library-to-library transitive dependencies.

Reads from: knowledge-graph/data/gradle-dependency-tree.txt
Creates: LIB_DEPENDS_ON relationships (ExternalLibrary → ExternalLibrary)

This file is generated by running:
    ./gradlew :deployment:dependencies --configuration appianLib > data/gradle-dependency-tree.txt
"""

import re
import logging
from pathlib import Path

from extractors import BaseExtractor
from graph.neo4j_client import GraphClient

logger = logging.getLogger(__name__)

# Regex to parse a dependency tree line
# Matches: |    +--- org.springframework:spring-context:6.2.19
# Or:      |    \--- com.google.guava:guava:33.6.0-jre
# Or:      |    +--- com.google.guava:guava:33.0.0-jre -> 33.6.0-jre
TREE_LINE_PATTERN = re.compile(
    r'^([| \\+\-]+)(\S+):(\S+):(\S+?)(?:\s+->\s+(\S+))?(?:\s+\([\w*]+\))?$'
)

# Matches constraint lines: +--- org.junit.jupiter:junit-jupiter:6.0.2 (c)
CONSTRAINT_MARKER = " (c)"


class LibTransitivityExtractor(BaseExtractor):
    """Extracts library-to-library transitive dependencies from Gradle dependency tree."""

    @property
    def name(self) -> str:
        return "Library Transitivity Extractor"

    def extract(self):
        tree_file = Path(__file__).parent.parent / "data" / "gradle-dependency-tree.txt"

        if not tree_file.exists():
            # Try to generate it automatically
            generated = self._try_generate_tree_file(tree_file)
            if not generated:
                logger.warning("  Dependency tree file not found and could not be generated.")
                logger.warning("  To generate manually, run from the ae repo root:")
                logger.warning("    ./gradlew :deployment:dependencies > <path>/data/gradle-dependency-tree.txt")
                logger.warning("  Skipping library transitivity extraction.")
                return

        logger.info(f"  Parsing dependency tree from: {tree_file}")
        content = tree_file.read_text(encoding="utf-8", errors="ignore")

        # Parse the tree into parent→child relationships
        lib_deps = self._parse_tree(content)
        logger.info(f"  Found {len(lib_deps)} library→library transitive dependency relationships")

        # Get known library coordinates from graph
        results = self.client.run_query("MATCH (lib:ExternalLibrary) RETURN lib.coordinate AS coord")
        known_libs = {r["coord"] for r in results}

        # Create LIB_DEPENDS_ON edges
        edges = []
        for parent_coord, child_coord in lib_deps:
            if parent_coord in known_libs and child_coord in known_libs:
                edges.append({
                    "from_id": parent_coord,
                    "to_id": child_coord,
                })

        # Deduplicate
        seen = set()
        unique_edges = []
        for e in edges:
            key = (e["from_id"], e["to_id"])
            if key not in seen:
                seen.add(key)
                unique_edges.append(e)

        if unique_edges:
            self.client.batch_create_relationships(
                "LIB_DEPENDS_ON", unique_edges,
                from_label="ExternalLibrary", to_label="ExternalLibrary",
                from_key="coordinate", to_key="coordinate",
            )
        logger.info(f"  Created {len(unique_edges)} LIB_DEPENDS_ON edges (library→library transitivity)")

        # Log some examples
        if unique_edges[:5]:
            logger.info("  Sample transitive dependencies:")
            for e in unique_edges[:10]:
                logger.info(f"    {e['from_id']} → {e['to_id']}")


    def _try_generate_tree_file(self, tree_file: Path) -> bool:
        """
        Try to auto-generate the dependency tree file by running Gradle.
        Scans ALL modules for complete transitive dependency coverage.
        Only works if Gradle is available and can connect to artifact repos (VPN).
        Returns True if successful.
        """
        import subprocess

        gradlew = self.repo_root / "gradlew"
        if not gradlew.exists():
            logger.info("  gradlew not found — cannot auto-generate dependency tree")
            return False

        logger.info("  Dependency tree file missing. Attempting to generate via Gradle...")
        logger.info("  (This requires VPN/artifact server access. Scanning ALL modules.)")

        # Ensure data directory exists
        tree_file.parent.mkdir(parents=True, exist_ok=True)

        try:
            # Root-level ./gradlew dependencies doesn't show subproject external deps.
            # Always use per-module scanning for complete transitive coverage.
            return self._generate_per_module(tree_file)

        except subprocess.TimeoutExpired:
            logger.warning("  Gradle timed out — VPN may not be connected")
            if tree_file.exists():
                tree_file.unlink()
            return False
        except Exception as e:
            logger.warning(f"  Failed to generate dependency tree: {e}")
            if tree_file.exists():
                tree_file.unlink()
            return False

    def _generate_per_module(self, tree_file: Path) -> bool:
        """Generate dependency tree by scanning all modules individually. Supports resume."""
        import subprocess

        gradlew = self.repo_root / "gradlew"

        # Get all module gradle paths from the graph
        results = self.client.run_query(
            "MATCH (m:Module) RETURN m.gradlePath AS path ORDER BY path"
        )
        all_modules = [r["path"] for r in results if r["path"] and r["path"] != ":"]

        # Check for existing partial file — resume from where we left off
        already_scanned = set()
        if tree_file.exists() and tree_file.stat().st_size > 100:
            existing_content = tree_file.read_text(encoding="utf-8", errors="ignore")
            # Extract modules already scanned (marked with === :module:path ===)
            import re
            already_scanned = set(re.findall(r'^=== (.+?) ===$', existing_content, re.MULTILINE))
            if already_scanned:
                logger.info(f"    Resuming: {len(already_scanned)} modules already scanned, {len(all_modules) - len(already_scanned)} remaining")
                print(f"    📋 Resuming from previous run — {len(already_scanned)}/{len(all_modules)} already done")

        remaining_modules = [m for m in all_modules if m not in already_scanned]

        if not remaining_modules:
            logger.info(f"    All {len(all_modules)} modules already scanned. Nothing to do.")
            return True

        logger.info(f"    Scanning {len(remaining_modules)} modules for dependencies...")

        # Open in append mode if resuming, write mode if fresh
        mode = "a" if already_scanned else "w"
        with open(tree_file, mode) as f:
            scanned = len(already_scanned)
            failed = 0
            for idx, module_path in enumerate(remaining_modules, 1):
                total_idx = len(already_scanned) + idx
                try:
                    result = subprocess.run(
                        [str(gradlew), f"{module_path}:dependencies", "--quiet"],
                        cwd=str(self.repo_root),
                        capture_output=True,
                        text=True,
                        timeout=60,  # 1 minute timeout per module
                    )
                    if result.returncode == 0 and result.stdout.strip():
                        f.write(f"\n=== {module_path} ===\n")
                        f.write(result.stdout)
                        f.flush()  # Flush after each module so progress is saved on crash
                        scanned += 1
                        print(f"    [{total_idx}/{len(all_modules)}] ✓ {module_path} (scanned: {scanned}, failed: {failed})")
                    else:
                        failed += 1
                        print(f"    [{total_idx}/{len(all_modules)}] ✗ {module_path} (no output or error)")
                except subprocess.TimeoutExpired:
                    failed += 1
                    print(f"    [{total_idx}/{len(all_modules)}] ⏱ {module_path} (timed out)")
                except KeyboardInterrupt:
                    # The current module might be partially written — remove it
                    f.flush()
                    f.close()
                    # Re-open and remove the last partial entry (the current module)
                    content = tree_file.read_text(encoding="utf-8", errors="ignore")
                    last_marker = content.rfind(f"\n=== {module_path} ===\n")
                    if last_marker != -1:
                        # Truncate the file to remove the partial entry
                        tree_file.write_text(content[:last_marker], encoding="utf-8")
                        print(f"\n    ⚠️  Interrupted at [{total_idx}/{len(all_modules)}] ({module_path}). Partial output removed.")
                    else:
                        print(f"\n    ⚠️  Interrupted at [{total_idx}/{len(all_modules)}]. Progress saved.")
                    print(f"    Run the same command again to resume — will restart from {module_path}.")
                    return tree_file.stat().st_size > 1000
                except Exception as e:
                    failed += 1
                    print(f"    [{total_idx}/{len(all_modules)}] ✗ {module_path} (error: {e})")

                # Also log to logger every 50 modules
                if idx % 50 == 0:
                    logger.info(f"    Progress: {total_idx}/{len(all_modules)} — {scanned} scanned, {failed} failed")

        file_size = tree_file.stat().st_size if tree_file.exists() else 0
        logger.info(f"  ✓ Generated dependency tree: {file_size:,} bytes ({scanned} modules scanned, {failed} failed)")

        if file_size < 1000:
            if tree_file.exists():
                tree_file.unlink()
            return False

        return True

    def _parse_tree(self, content: str) -> list[tuple[str, str]]:
        """
        Parse Gradle dependency tree output into parent→child pairs for external libraries.
        Uses character-counting for indentation to track tree depth.
        """
        dependencies = []
        # Stack tracks (depth, coordinate_or_none)
        # coordinate_or_none is None for project entries, a string for library entries
        stack: list[tuple[int, str | None]] = []

        for line in content.splitlines():
            # Must contain +--- or \--- to be a dependency line
            if "+---" not in line and "\\---" not in line:
                continue

            # Skip constraints (c)
            if line.rstrip().endswith("(c)"):
                continue

            # Calculate depth: count characters before +--- or \---
            marker_pos = line.find("+---")
            if marker_pos == -1:
                marker_pos = line.find("\\---")
            if marker_pos == -1:
                continue
            depth = marker_pos

            # Extract the dependency part after the marker
            dep_part = line[marker_pos + 4:].strip()

            # Remove trailing markers like (*) or (n)
            dep_part = re.sub(r'\s*\(\*\)\s*$', '', dep_part)
            dep_part = re.sub(r'\s*\(n\)\s*$', '', dep_part)

            # Determine if this is a project or a library
            if dep_part.startswith("project :"):
                # Internal project — push None coordinate
                stack = [(d, c) for d, c in stack if d < depth]
                stack.append((depth, None))
                continue

            # Parse as library: group:artifact:version [-> resolvedVersion]
            parts = dep_part.split(":")
            if len(parts) < 3:
                continue

            group = parts[0]
            artifact = parts[1]
            coordinate = f"{group}:{artifact}"

            # Pop stack to find parent at lower depth
            stack = [(d, c) for d, c in stack if d < depth]

            # Find the nearest library parent (skip None/project entries)
            parent_coord = None
            for d, c in reversed(stack):
                if c is not None:
                    parent_coord = c
                    break

            if parent_coord and parent_coord != coordinate:
                dependencies.append((parent_coord, coordinate))

            # Push current entry
            stack.append((depth, coordinate))

        return dependencies
